spring.application.name=funzel-backend

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/funzel_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# SECURITY ADMIN KEY
# ===============================
funzel.security.admin-api-key=FUNZEL_ADMIN_KEY_9F3A2D7C8B4E5A1F

# ===============================
# CAPTCHA (reCAPTCHA v3 REAL)
# ===============================
security.captcha.site-key=6LdIcFssAAAAAExggxBMUtGA9DmAUSaHPNMN-IpV
security.captcha.secret=6LdIcFssAAAAAHxutKNxVYRm1TRN3-6zgqcO5Ruy
security.captcha.min-score=0.5

# ===============================
# RATE LIMIT
# ===============================
funzel.rate-limit.general=30
funzel.rate-limit.contacto=5
funzel.rate-limit.donacion=3

# ===============================
# SERFINSA / DAVIVIENDA
# ===============================
serfinsa.test-mode=true
serfinsa.token-test=1781ee48-5389-482a-807f-48353f496c5c
serfinsa.token-live=${SERFINSA_TOKEN_LIVE:}
serfinsa.sandbox-url=https://testcheckout.redserfinsa.com:8087
serfinsa.live-url=https://www.serfinsacheckout.com

# PRUEBAS LOCALES FRONTEND
serfinsa.url-origin=https://funzel.es/pages/donar.html
serfinsa.url-redirect=https://funzel.es/pages/resultado-pago.html
